FROM openjdk:11

# Install X11 utilities and libraries
RUN apt-get update && apt-get install -y x11-apps libxext-dev libxrender-dev libxtst-dev

COPY . /usr/src/ticTacToe
WORKDIR /usr/src/ticTacToe/src

RUN javac Main.java

# Set up DISPLAY variable to connect to the X11 server
ENV DISPLAY=host.docker.internal:0

CMD ["java", "Main"]

